# Build settings
plugins:
  - jemoji
  - jekyll-paginate

# Site settings
title: "timfranssen.nl"
description: > # this means to ignore newlines until the next key
  My personal website and blog, where I publish articles without being dependent
  on some social medium.
paginate: 6
paginate_path: /archive/page:num/

author: 'Tim Franssen'
bio: Product developer, interaction designer, privacy advocate

domain: "timfranssen.nl"
url: "https://timfranssen.nl" # the base hostname & protocol for your site
baseurl: ""
