# Build settings
plugins:
  - jemoji
  - jekyll-paginate

# Site settings
title: "timfranssen.nl"
description: > # this means to ignore newlines until "email:"
  Just stuff I think up
paginate: 6
paginate_path: /archive/page:num/

author: 'Tim Franssen'
bio: Product developer, interaction designer, privacy advocate

domain: "timfranssen.nl"
url: "https://timfranssen.nl" # the base hostname & protocol for your site
baseurl: ""
